using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;
using System.Windows.Threading;

namespace QLKSSOFT.APP.Views
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();

            //set time clock
            var timer = new DispatcherTimer(new TimeSpan(0, 0, 1), DispatcherPriority.Normal, delegate
            {
                this.dateText.Text = "Thời điểm hiện tại là: " +  DateTime.Now.ToString("MM/dd/yyyy hh:mm:ss tt");
            }, this.Dispatcher);

        }

        private void StackPanel_MouseLeftButtonUp(object sender, MouseButtonEventArgs e)
        {
            var romWindow = new RoomWindow();
            romWindow.Show();
        }

        //private void c_dataGridScrollViewer_Loaded(object sender, RoutedEventArgs e)
        //{
        //    // Add MouseWheel support for the datagrid scrollviewer.
        //    c_dataGrid.AddHandler(MouseWheelEvent, new RoutedEventHandler(DataGridMouseWheelHorizontal), true);

        //    var list = new[]
        //    {
        //        new { Floor1 = 101, Floor2 = 201,Floor3 = 301 },
        //        new { Floor1 = 102, Floor2 = 202,Floor3 = 302 }
        //    }.ToList();

        //    c_dataGrid.ItemsSource = list;
        //}

        //private void DataGridMouseWheelHorizontal(object sender, RoutedEventArgs e)
        //{
        //    MouseWheelEventArgs eargs = (MouseWheelEventArgs)e;
        //    double x = (double)eargs.Delta;
        //    double y = c_dataGridScrollViewer.VerticalOffset;
        //    c_dataGridScrollViewer.ScrollToVerticalOffset(y - x);
        //}

        //private void c_dataGrid_AutoGeneratedColumns(object sender, EventArgs e)
        //{
        //    TransformGroup transformGroup = new TransformGroup();
        //    transformGroup.Children.Add(new RotateTransform(90));
        //    foreach (DataGridColumn dataGridColumn in c_dataGrid.Columns)
        //    {
        //        if (dataGridColumn is DataGridTextColumn)
        //        {
        //            DataGridTextColumn dataGridTextColumn = dataGridColumn as DataGridTextColumn;

        //            Style style = new Style(dataGridTextColumn.ElementStyle.TargetType, dataGridTextColumn.ElementStyle.BasedOn);
        //            style.Setters.Add(new Setter(TextBlock.MarginProperty, new Thickness(0, 2, 0, 2)));
        //            style.Setters.Add(new Setter(TextBlock.LayoutTransformProperty, transformGroup));
        //            style.Setters.Add(new Setter(TextBlock.HorizontalAlignmentProperty, HorizontalAlignment.Center));

        //            Style editingStyle = new Style(dataGridTextColumn.EditingElementStyle.TargetType, dataGridTextColumn.EditingElementStyle.BasedOn);
        //            editingStyle.Setters.Add(new Setter(TextBox.MarginProperty, new Thickness(0, 2, 0, 2)));
        //            editingStyle.Setters.Add(new Setter(TextBox.LayoutTransformProperty, transformGroup));
        //            editingStyle.Setters.Add(new Setter(TextBox.HorizontalAlignmentProperty, HorizontalAlignment.Center));

        //            dataGridTextColumn.ElementStyle = style;
        //            dataGridTextColumn.EditingElementStyle = editingStyle;
        //        }
        //    }
        //    List<DataGridColumn> dataGridColumns = new List<DataGridColumn>();
        //    foreach (DataGridColumn dataGridColumn in c_dataGrid.Columns)
        //    {
        //        dataGridColumns.Add(dataGridColumn);
        //    }
        //    c_dataGrid.Columns.Clear();
        //    dataGridColumns.Reverse();
        //    foreach (DataGridColumn dataGridColumn in dataGridColumns)
        //    {
        //        c_dataGrid.Columns.Add(dataGridColumn);
        //    }
        //}
    }
}
